#pragma once

// 21 이상부터 시작해야 한다!!!
enum class PACKET_ID : short
{
	LOGIN_IN_REQ = 21,
	LOGIN_IN_RES = 22,

	ROOM_ENTER_REQ = 61,
	ROOM_ENTER_RES = 62,
	ROOM_ENTER_NEW_USER_NTF = 63,

	ROOM_LEAVE_REQ = 66,
	ROOM_LEAVE_RES = 67,
	ROOM_LEAVE_USER_NTF = 68,

	ROOM_CHAT_REQ = 76,
	ROOM_CHAT_RES = 77,
	ROOM_CHAT_NTF = 78,

	PK_READY_GAME_ROOM_REQ = 81,
	PK_READY_GAME_ROOM_RES = 82,
	PK_READY_GAME_ROOM_NTF = 83,

	PK_CANCEL_READY_GAME_ROOM_REQ = 86,
	PK_CANCEL_READY_GAME_ROOM_RES = 87,
	PK_CANCEL_READY_GAME_ROOM_NTF = 88,

	PK_START_GAME_ROOM_NTF = 91,
	PK_END_GAME_ROOM_NTF = 92,

	PK_PUT_AL_ROOM_REQ = 96,
	PK_PUT_AL_ROOM_RES = 97,
	PK_PUT_AL_ROOM_NTF = 98,

	MAX = 256
};